### ISSUE TITLE
[Feat] Assignment 7 : Todo 완료 여부 수정 기능

### ISSUE THREAD

**Issue by chyerin802** [chyerin802/wanted-pre-onboarding-frontend#20]
## Description
TODO의 체크박스를 통해 완료 여부를 수정

## Task
- [x] checkbox의 선택 여부를 완료 여부 상태로 관리
- [x] 상태가 변함에 따라 `isCompleted` 속성을 변경하는 Update 요청하도록 구현
- [x] Update 요청 함수 구현
