### ISSUE TITLE
[Feat] Assignment 2 : 회원가입 기능 & 비동기 처리

### ISSUE THREAD

**Issue by chyerin802** [chyerin802/wanted-pre-onboarding-frontend#8]
## Description
회원가입 페이지에서 버튼을 클릭 시 회원가입을 진행
회원가입 성공 시 `/signin` 경로로 이동

## Task

- [x] `/auth/signup` API에 입력된 이메일과 비밀번호로 POST 요청 보내기
- [x] 201 Created 응답 시 `/signin` 경로로 이동
- [x] 요청 실패 시 예외 처리

### 요청

- URL: `/auth/signup`
- Method: `POST`
- Headers:
  - Content-Type: `application/json`
- Body:
  - email: string
  - password: string

### 응답 예시

- status: 201 Created
- body: 없음
